# Generated by Django 5.1.7 on 2025-05-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='frequency',
            field=models.CharField(choices=[('ONE_TIME', 'One Time'), ('EVERY_WEEK', 'Every Week(Discount 20%)'), ('EVERY_2_WEEKS', 'Every 2 Weeks(Discount 15%)'), ('EVERY_4_WEEKS', 'Every 4 Weeks(Discount 10%)')], max_length=20),
        ),
    ]
