# Generated by Django 5.1.7 on 2025-05-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingaddon',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
