# Generated by Django 5.1.7 on 2025-04-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quoterequest_delete_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='quoterequest',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='quoterequest',
            old_name='square_feet',
            new_name='squarefeet',
        ),
    ]
