# Generated by Django 5.1.7 on 2025-04-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_first_name_quoterequest_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='calculated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='change_linen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='deluxe_cleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='eco_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='handwash_dishes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='heavy_duty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='inside_cabinets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='inside_fridge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='inside_oven',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='laundry_folding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='load_dishwasher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='pet_hair_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('onetime', 'One Time(Deep)')], max_length=20),
        ),
    ]
