# Generated by Django 5.1.7 on 2025-05-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_addon_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonoption',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
