# Generated by Django 5.1.7 on 2025-04-07 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cleaning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('variable_price', models.BooleanField(default=False)),
                ('formula', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('apt', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('bathrooms', models.CharField(max_length=20)),
                ('bedrooms', models.CharField(max_length=20)),
                ('square_feet', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One Time'), ('EVERY_WEEK', 'Every Week(Discount 10%)'), ('EVERY_2_WEEKS', 'Every 2 Weeks(Discount 15%)'), ('EVERY_4_WEEKS', 'Every 4 Weeks(Discount 20%)')], max_length=20)),
                ('service_date', models.DateTimeField()),
                ('time_window', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=1)),
                ('preferred_team', models.CharField(default='No preference', max_length=100)),
                ('is_flexible', models.CharField(max_length=50)),
                ('referral_source', models.CharField(max_length=50)),
                ('access_method', models.CharField(choices=[('HOME', 'Someone will be home'), ('DOORMAN', 'Doorman'), ('LOCKBOX', 'Key in lockbox'), ('SMART_LOCK', 'Smart lock')], max_length=20)),
                ('access_instructions', models.TextField(blank=True, null=True)),
                ('parking_instructions', models.TextField(blank=True, null=True)),
                ('parking_cost', models.CharField(default='$0', max_length=10)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('payment_last_four', models.CharField(max_length=4)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
            ],
        ),
        migrations.CreateModel(
            name='BookingAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addonoption')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='api.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('send_text_reminders', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api.customer'),
        ),
        migrations.DeleteModel(
            name='Cleaning',
        ),
    ]
