# Generated by Django 5.1.7 on 2025-04-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_addonoption_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='created_at',
            new_name='date_created',
        ),
    ]
