# Generated by Django 5.1.7 on 2025-04-05 08:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_quoterequest_calculated_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('send_text_reminders', models.BooleanField(default=True)),
                ('service_type', models.CharField(choices=[('ONE_BEDROOM', 'HOME CLEANING: One Bedroom/Studio'), ('TWO_BEDROOM', 'HOME CLEANING: Two Bedroom'), ('THREE_BEDROOM', 'HOME CLEANING: Three Bedroom'), ('FOUR_BEDROOM', 'HOME CLEANING: Four Bedroom'), ('FIVE_BEDROOM', 'HOME CLEANING: Five Bedroom')], max_length=50)),
                ('bathrooms', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('square_feet', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One Time'), ('EVERY_WEEK', 'Every Week(Discount 20%)'), ('EVERY_2_WEEKS', 'Every 2 Weeks(Discount 15%)'), ('EVERY_4_WEEKS', 'Every 4 Weeks(Discount 10%)')], max_length=50)),
                ('addons', models.JSONField(default=list)),
                ('street_address', models.CharField(max_length=200)),
                ('apartment', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('service_date', models.DateTimeField()),
                ('time_window', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('1', 'Needs deep cleaning'), ('2', 'Below average'), ('3', 'Average'), ('4', 'Above average'), ('5', 'Mostly just needs maintenance')], max_length=1)),
                ('preferred_team', models.CharField(default='No preference', max_length=50)),
                ('flexibility', models.CharField(max_length=50)),
                ('referral_source', models.CharField(max_length=50)),
                ('access_method', models.CharField(max_length=100)),
                ('access_instructions', models.TextField(blank=True)),
                ('parking_instructions', models.TextField(blank=True)),
                ('parking_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('special_instructions', models.TextField(blank=True)),
                ('tip', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
